# Generated by Django 2.1.3 on 2018-11-08 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preferred_rigidity', models.CharField(choices=[('soft', 'Soft'), ('medium', 'Medium'), ('solid', 'Solid')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Code should have only latin symbols and numbers.', regex='^\\w+$')])),
                ('manufacturer', models.SlugField(max_length=64)),
                ('type', models.CharField(choices=[('chair', 'Chair'), ('desk', 'Desk'), ('sofa', 'Sofa'), ('table', 'Table'), ('bed', 'Bed'), ('cupboard', 'Cupboard')], max_length=32)),
                ('is_public', models.BooleanField()),
                ('allowed_users', models.ManyToManyField(related_name='allowed_furniture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chair', 'Chair'), ('desk', 'Desk'), ('sofa', 'Sofa'), ('table', 'Table'), ('bed', 'Bed'), ('cupboard', 'Cupboard')], max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('incline', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)])),
                ('rigidity', models.CharField(choices=[('soft', 'Soft'), ('medium', 'Medium'), ('solid', 'Solid')], max_length=32)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartfurnitureapi.Furniture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='furniture',
            name='current_options',
            field=models.ManyToManyField(to='smartfurnitureapi.Options'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='current_users',
            field=models.ManyToManyField(related_name='current_furniture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='furniture',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_furniture', to=settings.AUTH_USER_MODEL),
        ),
    ]
