# Generated by Django 2.1.3 on 2018-11-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfurnitureapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='pending',
            field=models.BooleanField(default=True, verbose_name='Pending'),
        ),
    ]
