# Generated by Django 2.1.3 on 2018-12-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfurnitureapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
    ]
