# Generated by Django 2.1.3 on 2019-01-08 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfurnitureapi', '0002_remove_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='incline',
            field=models.FloatField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Incline'),
        ),
        migrations.AlterField(
            model_name='options',
            name='temperature',
            field=models.FloatField(blank=True, default=36.6, null=True, verbose_name='Temperature'),
        ),
    ]
