# Generated by Django 2.1.3 on 2019-01-10 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfurnitureapi', '0003_auto_20190108_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='height',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='options',
            name='incline',
            field=models.FloatField(default=95, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Incline'),
        ),
        migrations.AlterField(
            model_name='options',
            name='length',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='options',
            name='temperature',
            field=models.FloatField(default=36.6, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='options',
            name='width',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Width'),
        ),
    ]
